version: 2
jobs:
  python36:
    docker:
      - image: circleci/python:3.6
      - image: circleci/redis:4

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            pip install --user tox
            echo 'export PATH="$PATH":"$HOME"/.local/bin' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: run tests
          command: |
            mkdir /tmp/tox_test_results
            tox -- --cov=redbeat --junitxml=/tmp/tox_test_results/unittests.xml
      - store_test_results:
          path: /tmp/tox_test_results
  python27:
    docker:
      - image: circleci/python:2.7
      - image: circleci/redis:4

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            pip install --user tox
            echo 'export PATH="$PATH":"$HOME"/.local/bin' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: run tests
          command: |
            mkdir /tmp/tox_test_results
            tox -- --cov=redbeat --junitxml=/tmp/tox_test_results/unittests.xml
      - store_test_results:
          path: /tmp/tox_test_results



workflows:
  version: 2
  test:
    jobs:
      - python36
      - python27
