version: 2
jobs:
  # TODO: add caching
  python36:
    docker:
      - image: circleci/python:3.6

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            pip install --user tox
            echo 'export PATH="$PATH":"$HOME"/.local/bin' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: run tests
          command: |
            mkdir /tmp/tox
            tox --skip-missing-interpreters -- --cov=redbeat --junitxml=/tmp/tox/{envname}.xml
      - store_test_results:
          path: /tmp/tox
  python27:
    docker:
      - image: circleci/python:2.7

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            pip install --user tox
            echo 'export PATH="$PATH":"$HOME"/.local/bin' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: run tests
          command: |
            mkdir /tmp/tox
            tox --skip-missing-interpreters -- --cov=redbeat --junitxml=/tmp/tox/{envname}.xml
      - store_test_results:
          path: /tmp/tox



workflows:
  version: 2
  test:
    jobs:
      - python36
      - python27
